# Generated by Django 3.1.6 on 2021-02-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='created_date',
            field=models.DateTimeField(verbose_name='date of creation'),
        ),
    ]
