# Generated by Django 3.1.6 on 2021-02-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_auto_20210212_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='current_status',
            field=models.IntegerField(choices=[(1, 'TODO'), (2, 'IN_PROGRESS'), (3, 'DONE')], default=1),
        ),
    ]
