# Generated by Django 3.1.6 on 2021-02-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_task_current_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='current_status',
            field=models.TextField(choices=[('TODO', 'TODO'), ('IN_PROGRESS', 'IN_PROGRESS'), ('DONE', 'DONE')], default='TODO'),
        ),
    ]
