# Generated by Django 3.1.6 on 2021-02-18 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_auto_20210218_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name_of_bundle',
            new_name='parent_bundle',
        ),
    ]
